# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.6.3'

gem 'sinatra', '= 2.0.5'
gem 'thin', '= 1.7.2'
gem "mongo", "~> 2.9"
gem "bson_ext", "~> 1.5"

gem "mongoid", "~> 7.0"
